future: true
permalink: /:title/
url: http://houhx.github.io
name: Hou Student
author: Xiao
qq: 1315864629
email: houhx3@mail2.sysu.edu.cn

markdown: rdiscount

duoshuo: houhx
beian: 
cnzz: 
weibo: 
github: houhx
about: "这里是 houhx 的个人博客，创建于 2018 年。"

safe: true
paginate: 20
